name: Translation

on: push

jobs:
  translation:
    name: Run translation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: fabasoad/translation-action@v1.4.13
        id: translation
        with:
          provider: linguatools
          # api_key: ${{ secrets.YANDEX_API_KEY }}
          lang: 'en-ru'
          source: 'This is awesome project! Thank you'
      - name: Print translation result
        run: echo "${{ steps.translation.outputs.text }}"
